#!/usr/bin/env sh

xworkspaces() {
    json_spaces_list=$(wmctrl -d \
        | sed 's/^\([0-9]\).*\([-|\*]\).*$/{"id":\1, "f":\2}/' \
        | sed 's/-/false/' \
        | sed 's/\*/true/' \
        | sed '$!s/$/,/' \
        | tr '\n' ' ')
    echo "[${json_spaces_list}]"
}

hyprworkspaces() {
    focused_space=$(hyprctl -j monitors \
        | jaq "map(select(.focused)) | .[0].activeWorkspace.id")
    json_spaces_list=$(hyprctl -j workspaces \
        | jaq "[.[].id, 7] | max | [range(1;(.+1))] | map({id: ., f: (.==${focused_space})})" \
        | tr -d ' \t' \
        | tr '\n' ' ')
    echo "${json_spaces_list}"
}

if echo $XDG_SESSION_DESKTOP | rg -q Hyprland; then
    if echo $1 | rg -q focus; then
        hyprctl dispatch workspace $2
    else
        hyprworkspaces
        socat -u UNIX-CONNECT:/tmp/hypr/"$HYPRLAND_INSTANCE_SIGNATURE"/.socket2.sock - \
            | rg --line-buffered "workspace|mon(itor)?|screencast" \
            | while read -r line; do
            hyprworkspaces
        done
    fi
else
    if echo $1 | rg -q focus; then
        wmctrl -s $2
    else
        xworkspaces
        xprop -spy -root _NET_CURRENT_DESKTOP | while read -r _ ; do
            xworkspaces
        done
    fi
fi
